## 2019

In [19]:
import pandas as pd

In [20]:
df = pd.read_csv("C:/zzz/oil/scrape/use/brent/2019/DCOILBRENTEU19.csv")
df

    observation_date  DCOILBRENTEU
0         2019-01-02         54.06
1         2019-01-03         53.23
2         2019-01-04         55.64
3         2019-01-07         57.10
4         2019-01-08         56.91
..               ...           ...
255       2019-12-25           NaN
256       2019-12-26         69.26
257       2019-12-27         68.91
258       2019-12-30         68.30
259       2019-12-31         67.77

[260 rows x 2 columns]

In [22]:
df = df[["observation_date","DCOILBRENTEU"]].rename(columns={"observation_date":"Date","DCOILBRENTEU":"Price_Brent"})
df

           Date  Price_Brent
0    2019-01-02        54.06
1    2019-01-03        53.23
2    2019-01-04        55.64
3    2019-01-07        57.10
4    2019-01-08        56.91
..          ...          ...
255  2019-12-25          NaN
256  2019-12-26        69.26
257  2019-12-27        68.91
258  2019-12-30        68.30
259  2019-12-31        67.77

[260 rows x 2 columns]

In [25]:
import pandas as pd

# สมมติ df มีคอลัมน์ 'date' และ 'Price_Brent'
df['Date'] = pd.to_datetime(df['Date'])

# สร้างช่วงวันที่ครบทุกวัน
full_dates = pd.date_range(start='2019-01-01', end='2019-12-31', freq='D')

# ตั้ง DataFrame ใหม่โดยใช้ full_dates
df_full = pd.DataFrame({'Date': full_dates})

# Merge กับข้อมูลเดิม (left join) เพื่อให้มีทุกวัน
df_full = df_full.merge(df, on='Date', how='left')

# เติมค่า Price_Brent ที่เป็น NaN ด้วย linear interpolation
df_full['Price_Brent'] = df_full['Price_Brent'].interpolate(method='linear')

# ตรวจสอบ
df_full

          Date  Price_Brent
0   2019-01-01          NaN
1   2019-01-02    54.060000
2   2019-01-03    53.230000
3   2019-01-04    55.640000
4   2019-01-05    56.126667
..         ...          ...
360 2019-12-27    68.910000
361 2019-12-28    68.706667
362 2019-12-29    68.503333
363 2019-12-30    68.300000
364 2019-12-31    67.770000

[365 rows x 2 columns]

In [40]:
df_full.isna().sum()

Date           0
Price_Brent    0
dtype: int64

In [39]:
nan_rows = df_full[df_full["Price_Brent"].isna()]

nan_rows

Empty DataFrame
Columns: [Date, Price_Brent]
Index: []

In [37]:
# 50.57

# เติมค่าแถวแรกด้วยค่าก่อนหน้า (50.57)
df_full.loc[0, 'Price_Brent'] = 50.57

# เติมค่า NaN ที่เหลือด้วย linear interpolation
df_full['Price_Brent'] = df_full['Price_Brent'].interpolate(method='linear')

# ตรวจสอบ 5 แถวแรก
df_full

          Date  Price_Brent
0   2019-01-01    50.570000
1   2019-01-02    54.060000
2   2019-01-03    53.230000
3   2019-01-04    55.640000
4   2019-01-05    56.126667
..         ...          ...
360 2019-12-27    68.910000
361 2019-12-28    68.706667
362 2019-12-29    68.503333
363 2019-12-30    68.300000
364 2019-12-31    67.770000

[365 rows x 2 columns]

In [41]:
# ตั้งชื่อไฟล์ brent 2019 เก็บไฟล์บน C:\zzz\oil\scrape\use\brent\data

import os

# สร้างโฟลเดอร์ถ้ายังไม่มี
output_dir = r"C:\zzz\oil\scrape\use\brent\data"
os.makedirs(output_dir, exist_ok=True)

# กำหนด path ของไฟล์
output_file = os.path.join(output_dir, "brent2019.csv")

# บันทึกเป็น CSV
df_full.to_csv(output_file, index=False)

print(f"Exported CSV to: {output_file}")

Exported CSV to: C:\zzz\oil\scrape\use\brent\data\brent2019.csv