## 2022

In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("C:/zzz/oil/scrape/use/brent/2022/DCOILBRENTEU22.csv")
df

    observation_date  DCOILBRENTEU
0         2022-01-03         78.25
1         2022-01-04         79.39
2         2022-01-05         80.60
3         2022-01-06         81.99
4         2022-01-07         82.28
..               ...           ...
255       2022-12-26           NaN
256       2022-12-27           NaN
257       2022-12-28         81.70
258       2022-12-29         80.96
259       2022-12-30         82.82

[260 rows x 2 columns]

In [3]:
df = df[["observation_date","DCOILBRENTEU"]].rename(columns={"observation_date":"Date","DCOILBRENTEU":"Price_Brent"})
df

           Date  Price_Brent
0    2022-01-03        78.25
1    2022-01-04        79.39
2    2022-01-05        80.60
3    2022-01-06        81.99
4    2022-01-07        82.28
..          ...          ...
255  2022-12-26          NaN
256  2022-12-27          NaN
257  2022-12-28        81.70
258  2022-12-29        80.96
259  2022-12-30        82.82

[260 rows x 2 columns]

In [4]:
import pandas as pd

# สมมติ df มีคอลัมน์ 'date' และ 'Price_Brent'
df['Date'] = pd.to_datetime(df['Date'])

# สร้างช่วงวันที่ครบทุกวัน
full_dates = pd.date_range(start='2022-01-01', end='2022-12-31', freq='D')

# ตั้ง DataFrame ใหม่โดยใช้ full_dates
df_full = pd.DataFrame({'Date': full_dates})

# Merge กับข้อมูลเดิม (left join) เพื่อให้มีทุกวัน
df_full = df_full.merge(df, on='Date', how='left')

# เติมค่า Price_Brent ที่เป็น NaN ด้วย linear interpolation
df_full['Price_Brent'] = df_full['Price_Brent'].interpolate(method='linear')

# ตรวจสอบ
df_full

          Date  Price_Brent
0   2022-01-01          NaN
1   2022-01-02          NaN
2   2022-01-03        78.25
3   2022-01-04        79.39
4   2022-01-05        80.60
..         ...          ...
360 2022-12-27        81.85
361 2022-12-28        81.70
362 2022-12-29        80.96
363 2022-12-30        82.82
364 2022-12-31        82.82

[365 rows x 2 columns]

In [5]:
df_full.isna().sum()

Date           0
Price_Brent    2
dtype: int64

In [10]:
nan_rows = df_full[df_full["Price_Brent"].isna()]

nan_rows

Empty DataFrame
Columns: [Date, Price_Brent]
Index: []

In [9]:
import pandas as pd

# หา index ของแถวที่เป็น NaN
nan_index = df_full[df_full["Price_Brent"].isna()].index

# สร้าง list ของ index ที่ต้องการ (ก่อนหน้า + แถว NaN + หลัง)
rows_to_print = []
for i in nan_index:
    if i-1 >= 0:
        rows_to_print.append(i-1)  # แถวก่อนหน้า
    rows_to_print.append(i)        # แถวที่เป็น NaN
    if i+1 < len(df_full):
        rows_to_print.append(i+1)  # แถวหลัง

# เอาเฉพาะ index ไม่ซ้ำ
rows_to_print = sorted(set(rows_to_print))

# แสดงผล
df_full.loc[rows_to_print]

Empty DataFrame
Columns: [Date, Price_Brent]
Index: []

In [12]:
# 77.24

# เติมค่าแถวแรกด้วยค่าก่อนหน้า
df_full.loc[0, 'Price_Brent'] = 77.24

# เติมค่า NaN ที่เหลือด้วย linear interpolation
df_full['Price_Brent'] = df_full['Price_Brent'].interpolate(method='linear')

# แสดงผล 5 แถวแรกแบบทศนิยม 2 ตำแหน่ง
pd.options.display.float_format = '{:.2f}'.format
df_full.head()

        Date  Price_Brent
0 2022-01-01        77.24
1 2022-01-02        77.75
2 2022-01-03        78.25
3 2022-01-04        79.39
4 2022-01-05        80.60

In [13]:
# ตั้งชื่อไฟล์ brent 2022 เก็บไฟล์บน C:\zzz\oil\scrape\use\brent\data

import os

# สร้างโฟลเดอร์ถ้ายังไม่มี
output_dir = r"C:\zzz\oil\scrape\use\brent\data"
os.makedirs(output_dir, exist_ok=True)

# กำหนด path ของไฟล์
output_file = os.path.join(output_dir, "brent2022.csv")

# บันทึกเป็น CSV
df_full.to_csv(output_file, index=False)

print(f"Exported CSV to: {output_file}")

Exported CSV to: C:\zzz\oil\scrape\use\brent\data\brent2022.csv