## 2020

In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("C:/zzz/oil/scrape/use/brent/2020/DCOILBRENTEU20.csv")
df

    observation_date  DCOILBRENTEU
0         2020-01-02         67.05
1         2020-01-03         69.08
2         2020-01-06         70.25
3         2020-01-07         68.74
4         2020-01-08         67.31
..               ...           ...
256       2020-12-25           NaN
257       2020-12-28         50.88
258       2020-12-29         50.44
259       2020-12-30         50.74
260       2020-12-31         51.22

[261 rows x 2 columns]

In [3]:
df = df[["observation_date","DCOILBRENTEU"]].rename(columns={"observation_date":"Date","DCOILBRENTEU":"Price_Brent"})
df

           Date  Price_Brent
0    2020-01-02        67.05
1    2020-01-03        69.08
2    2020-01-06        70.25
3    2020-01-07        68.74
4    2020-01-08        67.31
..          ...          ...
256  2020-12-25          NaN
257  2020-12-28        50.88
258  2020-12-29        50.44
259  2020-12-30        50.74
260  2020-12-31        51.22

[261 rows x 2 columns]

In [4]:
import pandas as pd

# สมมติ df มีคอลัมน์ 'date' และ 'Price_Brent'
df['Date'] = pd.to_datetime(df['Date'])

# สร้างช่วงวันที่ครบทุกวัน
full_dates = pd.date_range(start='2020-01-01', end='2020-12-31', freq='D')

# ตั้ง DataFrame ใหม่โดยใช้ full_dates
df_full = pd.DataFrame({'Date': full_dates})

# Merge กับข้อมูลเดิม (left join) เพื่อให้มีทุกวัน
df_full = df_full.merge(df, on='Date', how='left')

# เติมค่า Price_Brent ที่เป็น NaN ด้วย linear interpolation
df_full['Price_Brent'] = df_full['Price_Brent'].interpolate(method='linear')

# ตรวจสอบ
df_full

          Date  Price_Brent
0   2020-01-01          NaN
1   2020-01-02        67.05
2   2020-01-03        69.08
3   2020-01-04        69.47
4   2020-01-05        69.86
..         ...          ...
361 2020-12-27        50.88
362 2020-12-28        50.88
363 2020-12-29        50.44
364 2020-12-30        50.74
365 2020-12-31        51.22

[366 rows x 2 columns]

In [5]:
df_full.isna().sum()

Date           0
Price_Brent    1
dtype: int64

In [10]:
nan_rows = df_full[df_full["Price_Brent"].isna()]

nan_rows

Empty DataFrame
Columns: [Date, Price_Brent]
Index: []

In [9]:
import pandas as pd

# หา index ของแถวที่เป็น NaN
nan_index = df_full[df_full["Price_Brent"].isna()].index

# สร้าง list ของ index ที่ต้องการ (ก่อนหน้า + แถว NaN + หลัง)
rows_to_print = []
for i in nan_index:
    if i-1 >= 0:
        rows_to_print.append(i-1)  # แถวก่อนหน้า
    rows_to_print.append(i)        # แถวที่เป็น NaN
    if i+1 < len(df_full):
        rows_to_print.append(i+1)  # แถวหลัง

# เอาเฉพาะ index ไม่ซ้ำ
rows_to_print = sorted(set(rows_to_print))

# แสดงผล
df_full.loc[rows_to_print]

Empty DataFrame
Columns: [Date, Price_Brent]
Index: []

In [8]:
# 67.77

# เติมค่าแถวแรกด้วยค่าก่อนหน้า (67.77)
df_full.loc[0, 'Price_Brent'] = 67.77

# เติมค่า NaN ที่เหลือด้วย linear interpolation
df_full['Price_Brent'] = df_full['Price_Brent'].interpolate(method='linear')

# ตรวจสอบ 5 แถวแรก
df_full

          Date  Price_Brent
0   2020-01-01        67.77
1   2020-01-02        67.05
2   2020-01-03        69.08
3   2020-01-04        69.47
4   2020-01-05        69.86
..         ...          ...
361 2020-12-27        50.88
362 2020-12-28        50.88
363 2020-12-29        50.44
364 2020-12-30        50.74
365 2020-12-31        51.22

[366 rows x 2 columns]

In [11]:
# ตั้งชื่อไฟล์ brent 2020 เก็บไฟล์บน C:\zzz\oil\scrape\use\brent\data

import os

# สร้างโฟลเดอร์ถ้ายังไม่มี
output_dir = r"C:\zzz\oil\scrape\use\brent\data"
os.makedirs(output_dir, exist_ok=True)

# กำหนด path ของไฟล์
output_file = os.path.join(output_dir, "brent2020.csv")

# บันทึกเป็น CSV
df_full.to_csv(output_file, index=False)

print(f"Exported CSV to: {output_file}")

Exported CSV to: C:\zzz\oil\scrape\use\brent\data\brent2020.csv