## 2021

In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("C:/zzz/oil/scrape/use/brent/2021/DCOILBRENTEU21.csv")
df

    observation_date  DCOILBRENTEU
0         2021-01-04         50.37
1         2021-01-05         53.16
2         2021-01-06         53.80
3         2021-01-07         53.70
4         2021-01-08         55.51
..               ...           ...
255       2021-12-27           NaN
256       2021-12-28           NaN
257       2021-12-29         78.63
258       2021-12-30         78.61
259       2021-12-31         77.24

[260 rows x 2 columns]

In [3]:
df = df[["observation_date","DCOILBRENTEU"]].rename(columns={"observation_date":"Date","DCOILBRENTEU":"Price_Brent"})
df

           Date  Price_Brent
0    2021-01-04        50.37
1    2021-01-05        53.16
2    2021-01-06        53.80
3    2021-01-07        53.70
4    2021-01-08        55.51
..          ...          ...
255  2021-12-27          NaN
256  2021-12-28          NaN
257  2021-12-29        78.63
258  2021-12-30        78.61
259  2021-12-31        77.24

[260 rows x 2 columns]

In [4]:
import pandas as pd

# สมมติ df มีคอลัมน์ 'date' และ 'Price_Brent'
df['Date'] = pd.to_datetime(df['Date'])

# สร้างช่วงวันที่ครบทุกวัน
full_dates = pd.date_range(start='2021-01-01', end='2021-12-31', freq='D')

# ตั้ง DataFrame ใหม่โดยใช้ full_dates
df_full = pd.DataFrame({'Date': full_dates})

# Merge กับข้อมูลเดิม (left join) เพื่อให้มีทุกวัน
df_full = df_full.merge(df, on='Date', how='left')

# เติมค่า Price_Brent ที่เป็น NaN ด้วย linear interpolation
df_full['Price_Brent'] = df_full['Price_Brent'].interpolate(method='linear')

# ตรวจสอบ
df_full

          Date  Price_Brent
0   2021-01-01          NaN
1   2021-01-02          NaN
2   2021-01-03          NaN
3   2021-01-04       50.370
4   2021-01-05       53.160
..         ...          ...
360 2021-12-27       77.274
361 2021-12-28       77.952
362 2021-12-29       78.630
363 2021-12-30       78.610
364 2021-12-31       77.240

[365 rows x 2 columns]

In [5]:
df_full.isna().sum()

Date           0
Price_Brent    3
dtype: int64

In [11]:
nan_rows = df_full[df_full["Price_Brent"].isna()]

nan_rows

Empty DataFrame
Columns: [Date, Price_Brent]
Index: []

In [10]:
import pandas as pd

# หา index ของแถวที่เป็น NaN
nan_index = df_full[df_full["Price_Brent"].isna()].index

# สร้าง list ของ index ที่ต้องการ (ก่อนหน้า + แถว NaN + หลัง)
rows_to_print = []
for i in nan_index:
    if i-1 >= 0:
        rows_to_print.append(i-1)  # แถวก่อนหน้า
    rows_to_print.append(i)        # แถวที่เป็น NaN
    if i+1 < len(df_full):
        rows_to_print.append(i+1)  # แถวหลัง

# เอาเฉพาะ index ไม่ซ้ำ
rows_to_print = sorted(set(rows_to_print))

# แสดงผล
df_full.loc[rows_to_print]

Empty DataFrame
Columns: [Date, Price_Brent]
Index: []

In [9]:
# 51.22

# เติมค่าแถวแรกด้วยค่าก่อนหน้า (51.22)
df_full.loc[0, 'Price_Brent'] = 51.22

# เติมค่า NaN ที่เหลือด้วย linear interpolation
df_full['Price_Brent'] = df_full['Price_Brent'].interpolate(method='linear')

# ตรวจสอบ 5 แถวแรก
df_full

          Date  Price_Brent
0   2021-01-01    51.220000
1   2021-01-02    50.936667
2   2021-01-03    50.653333
3   2021-01-04    50.370000
4   2021-01-05    53.160000
..         ...          ...
360 2021-12-27    77.274000
361 2021-12-28    77.952000
362 2021-12-29    78.630000
363 2021-12-30    78.610000
364 2021-12-31    77.240000

[365 rows x 2 columns]

In [12]:
# ตั้งชื่อไฟล์ brent 2021 เก็บไฟล์บน C:\zzz\oil\scrape\use\brent\data

import os

# สร้างโฟลเดอร์ถ้ายังไม่มี
output_dir = r"C:\zzz\oil\scrape\use\brent\data"
os.makedirs(output_dir, exist_ok=True)

# กำหนด path ของไฟล์
output_file = os.path.join(output_dir, "brent2021.csv")

# บันทึกเป็น CSV
df_full.to_csv(output_file, index=False)

print(f"Exported CSV to: {output_file}")

Exported CSV to: C:\zzz\oil\scrape\use\brent\data\brent2021.csv