In [1]:
import pandas as pd

In [3]:
df = pd.read_excel("C:/zzz/oil/scrape/use/levy/P06.xls")
df

,TABLE 6,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13,Unnamed: 14,Unnamed: 15,Unnamed: 16,Unnamed: 17
0,OIL FUND LEVIED ON PETROLEUM PRODUCTS,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,UNIT: Baht/Litre,NaN,NaN
2,NaN,OIL FUND,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,DATE,ULG,UGR,GASOHOL 95,NaN,NaN,GASOHOL 91,KI,HSD **,HSD **,HSD,HSD,LSD,FO,NaN,LPG (B/Kg),NaN,NaN
4,NaN,NaN,NaN,(E10),(E20),(E85),NaN,NaN,B7,NaN,B20,B5,NaN,(1500),LOW INCOME,COOKING,INDUSTRY,AUTOBILE
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1661,AVG,9.6,NaN,3,1.9,3.6,3,0,1.33871,NaN,NaN,0,0,0.06,0,-0.237161,-0.237161,-0.237161
1662,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1663,หมายเหตุ : * วันที่ 18 มี.ค. 56 ยกเลิกโครงสร้า...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1664,** วันที่ 1 ต.ค. 63 เปลี่ยนชื่อจ...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1665,*** วันที่ 1 พ.ค. 67 ยกเลิกการจำห...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [4]:
# แปลงและบันทึกเป็น CSV
df.to_csv("C:/zzz/oil/scrape/use/levy/P06.csv", index=False, encoding="utf-8-sig")

In [6]:
data = pd.read_csv("C:/zzz/oil/scrape/use/levy/P06.csv")
data

,TABLE 6,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13,Unnamed: 14,Unnamed: 15,Unnamed: 16,Unnamed: 17
0,OIL FUND LEVIED ON PETROLEUM PRODUCTS,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,UNIT: Baht/Litre,NaN,NaN
2,NaN,OIL FUND,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,DATE,ULG,UGR,GASOHOL 95,NaN,NaN,GASOHOL 91,KI,HSD **,HSD **,HSD,HSD,LSD,FO,NaN,LPG (B/Kg),NaN,NaN
4,NaN,NaN,NaN,(E10),(E20),(E85),NaN,NaN,B7,NaN,B20,B5,NaN,(1500),LOW INCOME,COOKING,INDUSTRY,AUTOBILE
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1661,AVG,9.6,NaN,3,1.8999999999999997,3.6,3,0,1.3387096774193548,NaN,NaN,0,0,0.06,0,-0.23716129032258068,-0.23716129032258068,-0.23716129032258068
1662,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1663,หมายเหตุ : * วันที่ 18 มี.ค. 56 ยกเลิกโครงสร้า...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1664,** วันที่ 1 ต.ค. 63 เปลี่ยนชื่อจ...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1665,*** วันที่ 1 พ.ค. 67 ยกเลิกการจำห...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [11]:
import pandas as pd

df = pd.read_excel("C:/zzz/oil/scrape/use/levy/P06.xls", header=5)  # header จริงอยู่แถว 6 (0-indexed)
print(df.columns.tolist())

['Unnamed: 0', 'Unnamed: 1', 'Unnamed: 2', '(E10)', '(E20)', '(E85)', 'Unnamed: 6', 'Unnamed: 7', 'B7', 'Unnamed: 9', 'B20', 'B5', 'Unnamed: 12', '(1500)', 'LOW INCOME', 'COOKING', 'INDUSTRY', 'AUTOBILE']

In [21]:
import pandas as pd

# อ่าน Excel ทั้งแผ่น
df = pd.read_excel("C:/zzz/oil/scrape/use/levy/P06.xls", header=None)

# แปลงทุกค่าในคอลัมน์ Date เป็น string
df[0] = df[0].astype(str)

# หา index ของปี 2019 และ 2020
start_idx = df[df[0] == '2019'].index[0]
end_idx = df[df[0] == '2020'].index[0]

# เลือกเฉพาะแถวปี 2019
df_2019 = df.iloc[start_idx+1:end_idx, :]

# กรองเฉพาะแถวที่ Date เป็นรูปแบบเดือน/วัน
df_2019 = df_2019[df_2019[0].str.match(r'^[A-Z]{3}-\d{1,2}$')]

# ดึงคอลัมน์ E10 (สมมติอยู่คอลัมน์ 3)
df_e10 = df_2019[[0, 3]].copy()
df_e10.columns = ['Date', 'E10']

# แปลง Date เป็น datetime
df_e10['Date'] = pd.to_datetime(df_e10['Date'] + '-2019', errors='coerce', format='%b-%d-%Y')

# ลบแถวที่แปลง Date ไม่ได้
df_e10 = df_e10.dropna(subset=['Date'])

# แปลง E10 เป็น numeric และเติม NaN ด้วย interpolate
df_e10['E10'] = pd.to_numeric(df_e10['E10'], errors='coerce')
df_e10['E10'] = df_e10['E10'].interpolate(method='linear')

# ตรวจสอบจำนวนแถวและ 5 แถวแรก
print(df_e10.shape)
print(df_e10.head())
print(df_e10.tail())

(62, 2)
           Date   E10
1161 2019-01-01  2.12
1162 2019-01-07  2.12
1163 2019-01-14  2.12
1164 2019-01-21  2.12
1165 2019-01-28  2.12
           Date     E10
1229 2019-12-02  1.1200
1230 2019-12-09  1.1200
1231 2019-12-16  1.1200
1232 2019-12-23  0.5886
1233 2019-12-30  0.1900

In [22]:
# --- สร้าง DataFrame ครบทุกวันปี 2019 ---
full_dates = pd.date_range(start='2019-01-01', end='2019-12-31', freq='D')
df_full = pd.DataFrame({'Date': full_dates})

# --- merge ข้อมูลสัปดาห์ลงทุกวัน ---
df_full = df_full.merge(df_e10, on='Date', how='left')

# --- เติมค่า E10 ด้วย forward fill ---
df_full['E10'] = df_full['E10'].fillna(method='ffill')

# --- ตรวจสอบ 10 แถวแรกและ 10 แถวสุดท้าย ---
print(df_full.head(10))
print(df_full.tail(10))

        Date   E10
0 2019-01-01  2.12
1 2019-01-02  2.12
2 2019-01-03  2.12
3 2019-01-04  2.12
4 2019-01-05  2.12
5 2019-01-06  2.12
6 2019-01-07  2.12
7 2019-01-08  2.12
8 2019-01-09  2.12
9 2019-01-10  2.12
          Date     E10
355 2019-12-22  1.1200
356 2019-12-23  0.5886
357 2019-12-24  0.5886
358 2019-12-25  0.5886
359 2019-12-26  0.5886
360 2019-12-27  0.5886
361 2019-12-28  0.5886
362 2019-12-29  0.5886
363 2019-12-30  0.1900
364 2019-12-31  0.1900

C:\Users\student.COE\AppData\Local\Temp\ipykernel_23420\223826995.py:9: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df_full['E10'] = df_full['E10'].fillna(method='ffill')

In [23]:
# --- save CSV ---
df_full.to_csv("C:/zzz/oil/scrape/use/levy/data/levy2019.csv", index=False, encoding="utf-8-sig")